#!/bin/bash -l

#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=10
#SBATCH --ntasks-per-core=2
#SBATCH --time=02:30:00

echo "executes on nodes:"
echo $SLUM_JOB_NODELIST

echo "output (if any follows:)"

if [ ! -z $1 ]; then
	if [ ! -d "$1" ]; then
		mkdir "$1"
	fi
fi 

export OMP_NUM_THREADS=10
aprun -B /users/stud06/hpcse-adi/omp/src/main -N 3238 --dt 1 --nsteps 10000 -t 10 --benchmark
